Лабораторна робота №5. Робота Рибчинчука Вадима, група ПП-31(2).

Додаємо пакет NumPy та побудови матриць та пророблення операцій з знаходження певних рядків та їх спрощення.

In [3]:
import numpy as np

Введення матриць для першого та другого завдання

In [13]:
print("LabWork#5")
# Задання матриці платежів для першого завдання
payoff_matrix1 = np.array([
    [1, 9, 6, 0],
    [-2, 3, 8, 4],
    [-5, -2, 10, -3],
    [7, 4, -2, -5]
])

#Задання матриці платежів для дрцгого завдання
payoff_matrix2 = np.array([
    [-1, -2, -2],
    [-3, -2, -1],
    [-1, -1, -1]
])


LabWork#5


Завдання 1. Обчислення та знаходження нижньої/верхньої ціни гри.

In [12]:

# Знаходження нижньої та верхньої ціни гри
lower_price1 = np.min(payoff_matrix1)
upper_price1 = np.max(payoff_matrix1)

# Знаходження мінімального та максимального значення для кожного рядка
min_row_values1 = np.min(payoff_matrix1, axis=1)
max_row_values1 = np.max(payoff_matrix1, axis=1)

# Знаходження мінімального та максимального значення для кожного стовпчика
min_column_values1 = np.min(payoff_matrix1, axis=0)
max_column_values1 = np.max(payoff_matrix1, axis=0)

# Знаходження мінімакс для стовпчиків (максимум по мінімумам)
minimax_column1 = np.min(np.max(payoff_matrix1, axis=0))

# Знаходження максмін для рядків (мінімум по максимумах)
maxmin_row1 = np.max(np.min(payoff_matrix1, axis=1))

# Виведення результатів
print("Завдання 1")
print("Матриця платежів:")
print(payoff_matrix1)
print("\nМінімальні значення для кожного рядка:", min_row_values1)
print("Максимальні значення для кожного рядка:", max_row_values1)
print("Мінімальні значення для кожного стовпчика:", min_column_values1)
print("Максимальні значення для кожного стовпчика:", max_column_values1)
print("Нижня ціна гри:", lower_price1)
print("Верхня ціна гри:", upper_price1)
print("Мінімакс для стовпчиків B:", minimax_column1)
print("Максмін для рядків A:", maxmin_row1)

Завдання 1
Матриця платежів:
[[ 1  9  6  0]
 [-2  3  8  4]
 [-5 -2 10 -3]
 [ 7  4 -2 -5]]

Мінімальні значення для кожного рядка: [ 0 -2 -5 -5]
Максимальні значення для кожного рядка: [ 9  8 10  7]
Мінімальні значення для кожного стовпчика: [-5 -2 -2 -5]
Максимальні значення для кожного стовпчика: [ 7  9 10  4]
Нижня ціна гри: -5
Верхня ціна гри: 10
Мінімакс для стовпчиків B: 4
Максмін для рядків A: 0


Завдання 2. Обчислення та знаходження нижньої/верхньої ціни гри. Визначте всі чисті стратегії обох супротивників. Побудуйте платіжну матрицю, вважаючи гравцем 1 сторону, яка обороняється.

In [14]:
# Знаходження нижньої та верхньої ціни гри
lower_price2 = np.min(payoff_matrix2)
upper_price2 = np.max(payoff_matrix2)

# Знаходження мінімального та максимального значення для кожного рядка
min_row_values2 = np.min(payoff_matrix2, axis=1)
max_row_values2 = np.max(payoff_matrix2, axis=1)

# Знаходження мінімального та максимального значення для кожного стовпчика
min_column_values2 = np.min(payoff_matrix2, axis=0)
max_column_values2 = np.max(payoff_matrix2, axis=0)

# Знаходження мінімакс для стовпчиків (максимум по мінімумам)
minimax_column2 = np.min(np.max(payoff_matrix2, axis=0))

# Знаходження максмін для рядків (мінімум по максимумах)
maxmin_row2 = np.max(np.min(payoff_matrix2, axis=1))

# Виведення результатів
print("Завдання 2")
print("Матриця платежів:")
print(payoff_matrix2)
print("\nМінімальні значення для кожного рядка:", min_row_values2)
print("Максимальні значення для кожного рядка:", max_row_values2)
print("Мінімальні значення для кожного стовпчика:", min_column_values2)
print("Максимальні значення для кожного стовпчика:", max_column_values2)
print("Нижня ціна гри:", lower_price2)
print("Верхня ціна гри:", upper_price2)
print("Мінімакс для стовпчиків B:", minimax_column2)
print("Максмін для рядків A:", maxmin_row2)

Завдання 2
Матриця платежів:
[[-1 -2 -2]
 [-3 -2 -1]
 [-1 -1 -1]]

Мінімальні значення для кожного рядка: [-2 -3 -1]
Максимальні значення для кожного рядка: [-1 -1 -1]
Мінімальні значення для кожного стовпчика: [-3 -2 -2]
Максимальні значення для кожного стовпчика: [-1 -1 -1]
Нижня ціна гри: -3
Верхня ціна гри: -1
Мінімакс для стовпчиків B: -1
Максмін для рядків A: -1
